notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

language: c

sudo: false

services:
  - docker

install:
 - docker build -t dockstore-cgpbigwig .

script:
 - docker images | grep -c dockstore-cgpbigwig
